version: "3.8"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USERNAME: saidu
      POSTGRES_PASSWORD: kamara12345
      JWT_SECRET: supersecret
    depends_on:
      - db
    networks:
      - thriftnet

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: thrift_store_db
      POSTGRES_USER: saidu
      POSTGRES_PASSWORD: kamara12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - thriftnet

volumes:
  pgdata:

networks:
  thriftnet:
    external: true